server.port=8084
spring.main.banner-mode=off
spring.main.web-application-type=servlet
# Force AWT Headless to false so Desktop.getDesktop() can launch File Explorer on Windows
java.awt.headless=false
